[project]
name = "simple-pdf-parser"
version = "1.0.0"
description = "Simple PDF text extractor using Gemini API"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "pymupdf==1.26.3",
  "tenacity==9.1.2",
  "google-genai==1.29.0",
  "python-dotenv>=1.1.1",
]
